export const BANGLADESH_UNIVERSITIES = [
  "University of Dhaka",
  "Bangladesh University of Engineering and Technology (BUET)",
  "North South University (NSU)",
  "BRAC University",
  "Jahangirnagar University",
  "University of Chittagong",
  "University of Rajshahi",
  "Shahjalal University of Science and Technology (SUST)",
  "Khulna University",
  "Independent University, Bangladesh (IUB)",
  "American International University-Bangladesh (AIUB)",
  "United International University (UIU)",
  "Ahsanullah University of Science and Technology (AUST)",
  "East West University (EWU)",
  "Daffodil International University (DIU)",
  "Bangladesh Agricultural University",
  "Islamic University of Technology (IUT)",
  "Military Institute of Science and Technology (MIST)",
  "Sher-e-Bangla Agricultural University",
  "Jagannath University",
  "Bangladesh University of Professionals (BUP)",
  "Chittagong University of Engineering and Technology (CUET)",
  "Rajshahi University of Engineering and Technology (RUET)",
  "Khulna University of Engineering and Technology (KUET)",
  "Dhaka Medical College",
  "Sir Salimullah Medical College",
  "Shaheed Suhrawardy Medical College",
  "Mymensingh Medical College",
  "Chittagong Medical College",
  "Rajshahi Medical College",
  "Sylhet MAG Osmani Medical College",
  "Comilla Medical College",
  "Rangpur Medical College",
  "International Islamic University Chittagong",
  "Green University of Bangladesh",
  "University of Liberal Arts Bangladesh (ULAB)",
  "Stamford University Bangladesh",
  "Southeast University",
  "State University of Bangladesh",
  "Primeasia University",
  "Northern University Bangladesh",
  "World University of Bangladesh",
  "City University",
  "Victoria University of Bangladesh",
  "Manarat International University",
  "Bangladesh University of Business and Technology (BUBT)",
  "Presidency University",
  "University of South Asia",
  "Bangladesh University",
  "Leading University",
  "Sylhet International University",
  "Metropolitan University",
  "Royal University of Dhaka",
  "University of Information Technology and Sciences (UITS)",
  "Asa University Bangladesh",
  "Bangabandhu Sheikh Mujibur Rahman Agricultural University",
  "Hajee Mohammad Danesh Science and Technology University",
  "Patuakhali Science and Technology University",
  "Noakhali Science and Technology University",
  "Jatiya Kabi Kazi Nazrul Islam University",
  "Comilla University",
  "Begum Rokeya University",
  "Pabna University of Science and Technology",
  "Bangabandhu Sheikh Mujibur Rahman Science and Technology University",
  "Barisal University",
  "Rangamati Science and Technology University",
  "Bangabandhu Sheikh Mujibur Rahman Maritime University",
  "Islamic University, Bangladesh",
  "Asian University of Bangladesh",
  "Atish Dipankar University of Science and Technology",
  "Barendra University",
  "Canadian University of Bangladesh",
  "Central Women's University",
  "Chittagong Independent University (CIU)",
  "Dhaka International University",
  "Exim Bank Agricultural University Bangladesh",
  "Fareast International University",
  "First Capital University of Bangladesh",
  "Gono Bishwabidyalay",
  "Hamdard University Bangladesh",
  "Isha Kha International University",
  "Ishakha International University",
  "Khwaja Yunus Ali University",
  "North East University Bangladesh",
  "North Western University",
  "Notre Dame University Bangladesh",
  "Pundra University of Science and Technology",
  "Rajshahi Science and Technology University",
  "Ranada Prasad Shaha University",
  "Shanto-Mariam University of Creative Technology",
  " Sheikh Fazlatunnesa Mujib Fisheries College",
  "Sonargaon University",
  "Southern University Bangladesh",
  "The People's University of Bangladesh",
  "University of Creative Technology Chittagong",
  "University of Global Village",
  "University of Science and Technology Chittagong",
  "Varendra University",
  "Z.H. Sikder University of Science and Technology",
  "Army University of Engineering and Technology (Qadirabad)",
  "Army University of Science and Technology (Saidpur)",
  "Bangladesh Army International University of Science and Technology",
  "Bangladesh Army University of Engineering and Technology",
  "Bangladesh Army University of Science and Technology",
  "CCN University of Science and Technology",
  "Cox's Bazar International University",
  "European University of Bangladesh",
  "Feni University",
  "German University Bangladesh",
  "Global University Bangladesh",
  "International University of Business Agriculture and Technology (IUBAT)",
  "Millennium University",
  "NPI University of Bangladesh",
  "Port City International University",
  "R.P. Shaha University",
  "The International University of Scholars",
  "Times University Bangladesh",
  "Trust University",
  "University of Asia Pacific",
  "University of Development Alternative",
  "University of South Asia",
  "Uttara University",
  // Adding more public/specialized universities
  "National University",
  "Bangladesh Open University",
  "Chittagong Veterinary and Animal Sciences University",
  "Sylhet Agricultural University",
  "Jessore University of Science and Technology",
  "Bangabandhu Sheikh Mujib Medical University (BSMMU)",
  "Bangabandhu Sheikh Mujibur Rahman Digital University",
  "Bangabandhu Sheikh Mujibur Rahman Aviation and Aerospace University",
  "Chandpur Science and Technology University",
  "Hobiganj Agricultural University",
  "Kurigram Agricultural University",
  "Sunamganj Science and Technology University",
  "Bangamata Sheikh Fojilatunnesa Mujib Science and Technology University",
  "Sheikh Hasina University",
  "Begum Fazilatunnessa Mujib Government College",
  // Colleges under National University often function as high-volume job seekers
  "Dhaka College",
  "Eden Mohila College",
  "Government Titumir College",
  "Kabi Nazrul Government College",
  "Government Bangla College",
  "Begum Badrunnessa Government Girls' College",
  "Government College of Applied Human Science",
  "Ananda Mohan College",
  "Carmichael College",
  "Brajalal College",
  "Rajshahi College",
  "Chittagong College",
  "Victoria College, Comilla",
  "M C College, Sylhet",
  "Gurudayal Government College",
  "Edward College, Pabna"
];
